/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as NightSkyImport } from './routes/night-sky'
import { Route as LoginImport } from './routes/login'
import { Route as LandingImport } from './routes/landing'
import { Route as LayoutImport } from './routes/_layout'
import { Route as NightSkyIndexImport } from './routes/night-sky.index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as NightSkyPublicationIdImport } from './routes/night-sky/$publicationId'
import { Route as LayoutUserstorypromptsImport } from './routes/_layout/user_story_prompts'
import { Route as LayoutStoriesImport } from './routes/_layout/stories'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutMembershipImport } from './routes/_layout/membership'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutConversationsImport } from './routes/_layout/conversations'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutSummarySummaryIdImport } from './routes/_layout/summary/$summaryId'
import { Route as LayoutConversationConversationIdImport } from './routes/_layout/conversation/$conversationId'
import { Route as LayoutConstellationConstellationIdImport } from './routes/_layout/constellation/$constellationId'

// Create/Update Routes

const TermsRoute = TermsImport.update({
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const NightSkyRoute = NightSkyImport.update({
  path: '/night-sky',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LandingRoute = LandingImport.update({
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const NightSkyIndexRoute = NightSkyIndexImport.update({
  path: '/',
  getParentRoute: () => NightSkyRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const NightSkyPublicationIdRoute = NightSkyPublicationIdImport.update({
  path: '/$publicationId',
  getParentRoute: () => NightSkyRoute,
} as any)

const LayoutUserstorypromptsRoute = LayoutUserstorypromptsImport.update({
  path: '/user_story_prompts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoriesRoute = LayoutStoriesImport.update({
  path: '/stories',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMembershipRoute = LayoutMembershipImport.update({
  path: '/membership',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutConversationsRoute = LayoutConversationsImport.update({
  path: '/conversations',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSummarySummaryIdRoute = LayoutSummarySummaryIdImport.update({
  path: '/summary/$summaryId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutConversationConversationIdRoute =
  LayoutConversationConversationIdImport.update({
    path: '/conversation/$conversationId',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutConstellationConstellationIdRoute =
  LayoutConstellationConstellationIdImport.update({
    path: '/constellation/$constellationId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/landing': {
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/night-sky': {
      preLoaderRoute: typeof NightSkyImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/conversations': {
      preLoaderRoute: typeof LayoutConversationsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/membership': {
      preLoaderRoute: typeof LayoutMembershipImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/stories': {
      preLoaderRoute: typeof LayoutStoriesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/user_story_prompts': {
      preLoaderRoute: typeof LayoutUserstorypromptsImport
      parentRoute: typeof LayoutImport
    }
    '/night-sky/$publicationId': {
      preLoaderRoute: typeof NightSkyPublicationIdImport
      parentRoute: typeof NightSkyImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/night-sky/': {
      preLoaderRoute: typeof NightSkyIndexImport
      parentRoute: typeof NightSkyImport
    }
    '/_layout/constellation/$constellationId': {
      preLoaderRoute: typeof LayoutConstellationConstellationIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/conversation/$conversationId': {
      preLoaderRoute: typeof LayoutConversationConversationIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/summary/$summaryId': {
      preLoaderRoute: typeof LayoutSummarySummaryIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutConversationsRoute,
    LayoutItemsRoute,
    LayoutMembershipRoute,
    LayoutSettingsRoute,
    LayoutStoriesRoute,
    LayoutUserstorypromptsRoute,
    LayoutIndexRoute,
    LayoutConstellationConstellationIdRoute,
    LayoutConversationConversationIdRoute,
    LayoutSummarySummaryIdRoute,
  ]),
  LandingRoute,
  LoginRoute,
  NightSkyRoute.addChildren([NightSkyPublicationIdRoute, NightSkyIndexRoute]),
  PrivacyRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
  TermsRoute,
])

/* prettier-ignore-end */
